### PR TITLE
FISH-10118 FISH-10119 collect JVM/Thread dump from a remote ssh node

### PR DESCRIPTION
**Pull request by NotedSalmon**
As explained in the Remote Instance design page.

**_Changes made to the `CollectorService`:_**
The `CollectorService` has been changed to look for remote instances. The `ExecuteCollection` has been changed so it calls a function called `getInstancesList` which will use an asadmin command `list-nodes --long` and `list-instances` to populate two fields. `instancesWithType`, which will contain a map of the instance name and its respective node type ("CONFIG" or "SSH") and `targetLists` which will contain a list of all the instances.

The `getInstancesList` function was previously named `getInstanceRoot` which would only get the root directory of the instance. This forces the Diagnostic Tool to only look for local instances and so it has been changed to fit the new purpose.

The switch statement determines if the user has set a target and which type it is. Depending on which TargetType it is, it will call the `getActiveCollectors` with a new parameter which will be used to determine the instance name.

In the ` getActiveCollectors` the function will call the `instancesWithType` to figure out if the instance is local or remote. depending on the outcome, it will either collect the logs and heap dump (currently forced to be local due to functionality issues with remote instances) or just collect the jvm report and thread dump.

If the targetType is `DOMAIN` then it will collect everything, calling a function called `addInstanceCollector` which will get all the instances in the server, check if it is local or remote and collect accordingly.

The previous function `getLocalCollectors` has been deleted as it is not necessary and it has repeated code from the other functions.

**_Changes made to the `DomainUtil`:_**
The changes made to `DomainUtil` have been minimal. I have changed the name of the function `getLocalInstances()` as the name is not true to its current functionality. Previously it was only gathering instances from local nodes, whereas now it looks for instances in all nodes.

**_How to Test_**
Copy branch into local directory
Go to directory and run `mvn clean install`
Go to target folder and copy the `.jar` file
paste the `.jar` file in **Payara Enterprise 5 ** `/payara5/glassfish/lib/asadmin/` and replace current diagnostics jar

On the Payara Server, create an SSH Node and create an instance for the respective SSH Node and start it.

use the command `./asadmin collect-diagnostics --target instanceInSSH`
`--target` can be used to target deployment groups too.

### CODE REVIEW

**Comment by breakponchito** [comment]
@NotedSalmon please provide steps how to test this

**Comment by breakponchito** [comment]
@NotedSalmon please provide steps how to test this

**Comment by NotedSalmon** [comment]
> @NotedSalmon please provide steps how to test this

Testing steps have now been provided

**Review by luiseufrasio — APPROVED** [review]
LGTM!

**Pull request merged**
